export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const COMPLETED_TODO = "COMPLETED_TODO";
export const CLEAR_COMPLETED_TODO = "CLEAR_COMPLETED_TODO";
export const FILTERED_TODO = "FILTERED_TODO";
